// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { ClearHistoryData, ClearHistoryResponses, GetHistoryData, GetHistoryResponses, LoadHistoryData, LoadHistoryResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class History {
    public static clearHistory<ThrowOnError extends boolean = false>(options?: Options<ClearHistoryData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<ClearHistoryResponses, unknown, ThrowOnError>({
            url: '/umbraco/usync/api/v1/history/ClearHistory',
            ...options
        });
    }
    
    public static getHistory<ThrowOnError extends boolean = false>(options?: Options<GetHistoryData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetHistoryResponses, unknown, ThrowOnError>({
            url: '/umbraco/usync/api/v1/history/GetHistory',
            ...options
        });
    }
    
    public static loadHistory<ThrowOnError extends boolean = false>(options?: Options<LoadHistoryData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<LoadHistoryResponses, unknown, ThrowOnError>({
            url: '/umbraco/usync/api/v1/history/HistoryInfo',
            ...options
        });
    }
}