// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
  ClearHistoryData,
  ClearHistoryErrors,
  ClearHistoryResponses,
  GetHistoryData,
  GetHistoryErrors,
  GetHistoryResponses,
  HistoryIsEnabledData,
  HistoryIsEnabledErrors,
  HistoryIsEnabledResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class History {
  public static clearHistory<ThrowOnError extends boolean = true>(
    options?: Options<ClearHistoryData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      ClearHistoryResponses,
      ClearHistoryErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/umbraco/usync/api/v1/history/ClearHistory",
      ...options,
    });
  }

  public static getHistory<ThrowOnError extends boolean = true>(
    options?: Options<GetHistoryData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      GetHistoryResponses,
      GetHistoryErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/umbraco/usync/api/v1/history/GetHistory",
      ...options,
    });
  }

  public static historyIsEnabled<ThrowOnError extends boolean = true>(
    options?: Options<HistoryIsEnabledData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      HistoryIsEnabledResponses,
      HistoryIsEnabledErrors,
      ThrowOnError
    >({
      security: [{ scheme: "bearer", type: "http" }],
      url: "/umbraco/usync/api/v1/history/HistoryIsEnabled",
      ...options,
    });
  }
}
