// This file is auto-generated by @hey-api/openapi-ts

import type {
  Client,
  ClientMeta,
  Options as Options2,
  RequestResult,
  TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  GetHistoryClearHistoryData,
  GetHistoryClearHistoryErrors,
  GetHistoryClearHistoryResponses,
  GetHistoryHistoryData,
  GetHistoryHistoryErrors,
  GetHistoryHistoryResponses,
  GetHistoryIsEnabledData,
  GetHistoryIsEnabledErrors,
  GetHistoryIsEnabledResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export const getHistoryClearHistory = <ThrowOnError extends boolean = false>(
  options?: Options<GetHistoryClearHistoryData, ThrowOnError>,
): RequestResult<
  GetHistoryClearHistoryResponses,
  GetHistoryClearHistoryErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetHistoryClearHistoryResponses,
    GetHistoryClearHistoryErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/umbraco/usync/api/v1/history/ClearHistory",
    ...options,
  });

export const getHistoryHistory = <ThrowOnError extends boolean = false>(
  options?: Options<GetHistoryHistoryData, ThrowOnError>,
): RequestResult<
  GetHistoryHistoryResponses,
  GetHistoryHistoryErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetHistoryHistoryResponses,
    GetHistoryHistoryErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/umbraco/usync/api/v1/history/History",
    ...options,
  });

export const getHistoryIsEnabled = <ThrowOnError extends boolean = false>(
  options?: Options<GetHistoryIsEnabledData, ThrowOnError>,
): RequestResult<
  GetHistoryIsEnabledResponses,
  GetHistoryIsEnabledErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetHistoryIsEnabledResponses,
    GetHistoryIsEnabledErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/umbraco/usync/api/v1/history/IsEnabled",
    ...options,
  });
