// This file is auto-generated by @hey-api/openapi-ts

export enum ChangeDetailType {
    NO_CHANGE = 'NoChange',
    CREATE = 'Create',
    UPDATE = 'Update',
    DELETE = 'Delete',
    ERROR = 'Error',
    WARNING = 'Warning'
}

export enum ChangeType {
    NO_CHANGE = 'NoChange',
    CREATE = 'Create',
    IMPORT = 'Import',
    EXPORT = 'Export',
    UPDATE = 'Update',
    DELETE = 'Delete',
    WILL_CHANGE = 'WillChange',
    INFORMATION = 'Information',
    ROLLEDBACK = 'Rolledback',
    FAIL = 'Fail',
    IMPORT_FAIL = 'ImportFail',
    MISMATCH = 'Mismatch',
    PARENT_MISSING = 'ParentMissing',
    HIDDEN = 'Hidden',
    CLEAN = 'Clean',
    REMOVED = 'Removed'
}

export type HistoryInfo = {
    actions: Array<USyncActionView>;
    date: string;
    username: string;
    method: string;
    filePath: string;
    changes: number;
    total: number;
};

export type USyncActionView = {
    key: string;
    name: string;
    handler: string;
    itemType: string;
    change: ChangeType;
    success: boolean;
    details: Array<USyncChange>;
    message?: string | null;
};

export type USyncChange = {
    success: boolean;
    name: string;
    path: string;
    oldValue: string;
    newValue: string;
    change: ChangeDetailType;
};

export type ClearHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/history/ClearHistory';
};

export type ClearHistoryResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type ClearHistoryResponse = ClearHistoryResponses[keyof ClearHistoryResponses];

export type GetHistoryData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/history/GetHistory';
};

export type GetHistoryResponses = {
    /**
     * OK
     */
    200: Array<HistoryInfo>;
};

export type GetHistoryResponse = GetHistoryResponses[keyof GetHistoryResponses];

export type LoadHistoryData = {
    body?: never;
    path?: never;
    query?: {
        filePath?: string;
    };
    url: '/umbraco/usync/api/v1/history/HistoryInfo';
};

export type LoadHistoryResponses = {
    /**
     * OK
     */
    200: HistoryInfo;
};

export type LoadHistoryResponse = LoadHistoryResponses[keyof LoadHistoryResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44338' | (string & {});
};