// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "https://localhost:44304/" | (string & {});
};

export enum ChangeDetailType {
  NO_CHANGE = "NoChange",
  CREATE = "Create",
  UPDATE = "Update",
  DELETE = "Delete",
  ERROR = "Error",
  WARNING = "Warning",
}

export enum ChangeType {
  NO_CHANGE = "NoChange",
  CREATE = "Create",
  IMPORT = "Import",
  EXPORT = "Export",
  UPDATE = "Update",
  DELETE = "Delete",
  WILL_CHANGE = "WillChange",
  INFORMATION = "Information",
  ROLLEDBACK = "Rolledback",
  FAIL = "Fail",
  IMPORT_FAIL = "ImportFail",
  MISMATCH = "Mismatch",
  PARENT_MISSING = "ParentMissing",
  HIDDEN = "Hidden",
  CLEAN = "Clean",
  REMOVED = "Removed",
}

export type HistoryInfo = {
  actions: Array<USyncActionView>;
  date: string;
  username: string;
  method: string;
  filePath: string;
  changes: number | string;
  total: number | string;
};

export type USyncActionView = {
  key: string;
  name: string;
  handler: string;
  itemType: string;
  change: ChangeType;
  success: boolean;
  details: Array<USyncChange>;
  message?: null | string;
};

export type USyncChange = {
  success: boolean;
  name: string;
  path: string;
  oldValue: string;
  newValue: string;
  change: ChangeDetailType;
};

export type GetHistoryClearHistoryData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/umbraco/usync/api/v1/history/ClearHistory";
};

export type GetHistoryClearHistoryErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetHistoryClearHistoryResponses = {
  /**
   * OK
   */
  200: unknown;
};

export type GetHistoryHistoryData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/umbraco/usync/api/v1/history/History";
};

export type GetHistoryHistoryErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetHistoryHistoryResponses = {
  /**
   * OK
   */
  200: Array<HistoryInfo>;
};

export type GetHistoryHistoryResponse =
  GetHistoryHistoryResponses[keyof GetHistoryHistoryResponses];

export type GetHistoryIsEnabledData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/umbraco/usync/api/v1/history/IsEnabled";
};

export type GetHistoryIsEnabledErrors = {
  /**
   * The resource is protected and requires an authentication token
   */
  401: unknown;
};

export type GetHistoryIsEnabledResponses = {
  /**
   * OK
   */
  200: boolean;
};

export type GetHistoryIsEnabledResponse =
  GetHistoryIsEnabledResponses[keyof GetHistoryIsEnabledResponses];
