<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0</TargetFrameworks>

		<PackageId>uSync.Core</PackageId>

		<Description>
			Core serializers for uSync to read / write information to / from Umbraco CMS.
		</Description>

		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<ImplicitUsings>enable</ImplicitUsings>

		<PublishRepositoryUrl>true</PublishRepositoryUrl>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Umbraco.Cms.Web.Website"/>
		<PackageReference Include="Umbraco.Cms.Api.Management" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup>
		<None Include="readme.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
