<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <!-- umbraco site -->
  <ItemGroup>
    <PackageVersion Include="Our.Umbraco.ConditionalDisplayers" Version="16.6.0" />
    <PackageVersion Include="Umbraco.Cms" Version="18.0.0-rc2" />
    <PackageVersion Include="Umbraco.Cms.DevelopmentMode.Backoffice" Version="18.0.0-rc2" />
    <PackageVersion Include="Microsoft.ICU.ICU4C.Runtime" Version="72.1.0.3" />
    <PackageVersion Include="Clean.Core" Version="18.0.0-beta1" />
  </ItemGroup>
  <!-- umbraco libraries for packages -->
  <ItemGroup>
    <PackageVersion Include="Umbraco.Cms.Core" Version="18.0.0-rc3" />
    <PackageVersion Include="Umbraco.Cms.Web.Website" Version="18.0.0-rc3" />
    <PackageVersion Include="Umbraco.Cms.Api.Management" Version="18.0.0-rc3" />
  </ItemGroup>
  <!-- source link -->
  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.300" />
  </ItemGroup>
  <!-- testing -->
  <ItemGroup>
    <PackageVersion Include="Umbraco.Cms.Tests" Version="18.0.0-rc3" />
    <PackageVersion Include="Umbraco.Cms.Tests.Integration" Version="18.0.0-rc3" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.7.0" />
    <PackageVersion Include="NUnit3TestAdapter" Version="6.2.0" />
    <PackageVersion Include="coverlet.collector" Version="10.0.1" />
  </ItemGroup>
  <!-- command line -->
  <ItemGroup>
    <PackageVersion Include="NJsonSchema" Version="11.6.1" />
    <PackageVersion Include="CommandLineParser" Version="2.9.1" />
  </ItemGroup>
</Project>