<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<StaticWebAssetBasePath>/</StaticWebAssetBasePath>
		<Description>v15 management api for uSync</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.0" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Umbraco.Cms.Api.Management" Version="16.0.0-rc" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\uSync.BackOffice\uSync.BackOffice.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="wwwroot\App_Plugins\uSync\boot\TurbineBlades.jpg" />
	  <None Include="wwwroot\App_Plugins\uSync\boot\usynclogo.png" />
	</ItemGroup>
</Project>
