// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetActionsBySetData, GetActionsBySetErrors, GetActionsBySetResponses, GetAddOnsData, GetAddOnsErrors, GetAddOnSplashData, GetAddOnSplashErrors, GetAddOnSplashResponses, GetAddOnsResponses, GetCheckLegacyData, GetCheckLegacyErrors, GetCheckLegacyResponses, GetHandlerSettingsData, GetHandlerSettingsErrors, GetHandlerSettingsResponses, GetSetsData, GetSetsErrors, GetSetsResponses, GetSettingsData, GetSettingsErrors, GetSettingsResponses, GetSyncFileInfoData, GetSyncFileInfoErrors, GetSyncFileInfoResponses, PostCopyLegacyData, PostCopyLegacyErrors, PostCopyLegacyResponses, PostDownloadData, PostDownloadErrors, PostDownloadResponses, PostIgnoreLegacyData, PostIgnoreLegacyErrors, PostIgnoreLegacyResponses, PostImportData, PostImportErrors, PostImportResponses, PostMergeExportData, PostMergeExportErrors, PostMergeExportResponses, PostPerformData, PostPerformErrors, PostPerformResponses, PostProcessUploadData, PostProcessUploadErrors, PostProcessUploadResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getActionsBySet = <ThrowOnError extends boolean = false>(options?: Options<GetActionsBySetData, ThrowOnError>) => (options?.client ?? client).get<GetActionsBySetResponses, GetActionsBySetErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/usync/api/v1/ActionsBySet',
    ...options
});

export const postDownload = <ThrowOnError extends boolean = false>(options?: Options<PostDownloadData, ThrowOnError>) => (options?.client ?? client).post<PostDownloadResponses, PostDownloadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/usync/api/v1/Download',
    ...options
});

export const postImport = <ThrowOnError extends boolean = false>(options: Options<PostImportData, ThrowOnError>) => (options.client ?? client).post<PostImportResponses, PostImportErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/usync/api/v1/Import',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postPerform = <ThrowOnError extends boolean = false>(options: Options<PostPerformData, ThrowOnError>) => (options.client ?? client).post<PostPerformResponses, PostPerformErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/usync/api/v1/Perform',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const postProcessUpload = <ThrowOnError extends boolean = false>(options?: Options<PostProcessUploadData, ThrowOnError>) => (options?.client ?? client).post<PostProcessUploadResponses, PostProcessUploadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/usync/api/v1/ProcessUpload',
    ...options
});

export const getSyncFileInfo = <ThrowOnError extends boolean = false>(options?: Options<GetSyncFileInfoData, ThrowOnError>) => (options?.client ?? client).get<GetSyncFileInfoResponses, GetSyncFileInfoErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/usync/api/v1/SyncFileInfo',
    ...options
});

export const postMergeExport = <ThrowOnError extends boolean = false>(options?: Options<PostMergeExportData, ThrowOnError>) => (options?.client ?? client).post<PostMergeExportResponses, PostMergeExportErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/usync/api/v1/MergeExport',
    ...options
});

export const getCheckLegacy = <ThrowOnError extends boolean = false>(options?: Options<GetCheckLegacyData, ThrowOnError>) => (options?.client ?? client).get<GetCheckLegacyResponses, GetCheckLegacyErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/usync/api/v1/CheckLegacy',
    ...options
});

export const postCopyLegacy = <ThrowOnError extends boolean = false>(options?: Options<PostCopyLegacyData, ThrowOnError>) => (options?.client ?? client).post<PostCopyLegacyResponses, PostCopyLegacyErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/usync/api/v1/CopyLegacy',
    ...options
});

export const postIgnoreLegacy = <ThrowOnError extends boolean = false>(options?: Options<PostIgnoreLegacyData, ThrowOnError>) => (options?.client ?? client).post<PostIgnoreLegacyResponses, PostIgnoreLegacyErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/usync/api/v1/IgnoreLegacy',
    ...options
});

export const getAddOns = <ThrowOnError extends boolean = false>(options?: Options<GetAddOnsData, ThrowOnError>) => (options?.client ?? client).get<GetAddOnsResponses, GetAddOnsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/usync/api/v1/AddOns',
    ...options
});

export const getAddOnSplash = <ThrowOnError extends boolean = false>(options?: Options<GetAddOnSplashData, ThrowOnError>) => (options?.client ?? client).get<GetAddOnSplashResponses, GetAddOnSplashErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/usync/api/v1/AddOnSplash',
    ...options
});

export const getHandlerSettings = <ThrowOnError extends boolean = false>(options?: Options<GetHandlerSettingsData, ThrowOnError>) => (options?.client ?? client).get<GetHandlerSettingsResponses, GetHandlerSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/usync/api/v1/HandlerSettings',
    ...options
});

export const getSets = <ThrowOnError extends boolean = false>(options?: Options<GetSetsData, ThrowOnError>) => (options?.client ?? client).get<GetSetsResponses, GetSetsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/usync/api/v1/Sets',
    ...options
});

export const getSettings = <ThrowOnError extends boolean = false>(options?: Options<GetSettingsData, ThrowOnError>) => (options?.client ?? client).get<GetSettingsResponses, GetSettingsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/umbraco/usync/api/v1/Settings',
    ...options
});
