// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CheckLegacyData, CheckLegacyErrors, CheckLegacyResponses, CopyLegacyData, CopyLegacyErrors, CopyLegacyResponses, DownloadData, DownloadErrors, DownloadResponses, GetActionsBySetData, GetActionsBySetErrors, GetActionsBySetResponses, GetActionsData, GetActionsErrors, GetActionsResponses, GetAddOnsData, GetAddOnsErrors, GetAddonSplashData, GetAddonSplashErrors, GetAddonSplashResponses, GetAddOnsResponses, GetHandlerSetSettingsData, GetHandlerSetSettingsErrors, GetHandlerSetSettingsResponses, GetSetsData, GetSetsErrors, GetSetsResponses, GetSettingsData, GetSettingsErrors, GetSettingsResponses, GetSyncFileInfoData, GetSyncFileInfoErrors, GetSyncFileInfoResponses, IgnoreLegacyData, IgnoreLegacyErrors, IgnoreLegacyResponses, ImportSingleData, ImportSingleErrors, ImportSingleResponses, MergeExportFolderData, MergeExportFolderErrors, MergeExportFolderResponses, PerformActionData, PerformActionErrors, PerformActionResponses, ProcessUploadData, ProcessUploadErrors, ProcessUploadResponses, RunningData, RunningErrors, RunningResponses, StatusData, StatusErrors, StatusResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class ActionsService {
    /**
     * @deprecated
     */
    public static getActions<ThrowOnError extends boolean = true>(options?: Options<GetActionsData, ThrowOnError>): RequestResult<GetActionsResponses, GetActionsErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetActionsResponses, GetActionsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/Actions',
            ...options
        });
    }
    
    public static getActionsBySet<ThrowOnError extends boolean = true>(options?: Options<GetActionsBySetData, ThrowOnError>): RequestResult<GetActionsBySetResponses, GetActionsBySetErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetActionsBySetResponses, GetActionsBySetErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/ActionsBySet',
            ...options
        });
    }
    
    public static download<ThrowOnError extends boolean = true>(options?: Options<DownloadData, ThrowOnError>): RequestResult<DownloadResponses, DownloadErrors, ThrowOnError> {
        return (options?.client ?? client).post<DownloadResponses, DownloadErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/Download',
            ...options
        });
    }
    
    public static getSyncFileInfo<ThrowOnError extends boolean = true>(options?: Options<GetSyncFileInfoData, ThrowOnError>): RequestResult<GetSyncFileInfoResponses, GetSyncFileInfoErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetSyncFileInfoResponses, GetSyncFileInfoErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/GetSyncFileInfo',
            ...options
        });
    }
    
    public static importSingle<ThrowOnError extends boolean = true>(options?: Options<ImportSingleData, ThrowOnError>): RequestResult<ImportSingleResponses, ImportSingleErrors, ThrowOnError> {
        return (options?.client ?? client).post<ImportSingleResponses, ImportSingleErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/Import',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static performAction<ThrowOnError extends boolean = true>(options?: Options<PerformActionData, ThrowOnError>): RequestResult<PerformActionResponses, PerformActionErrors, ThrowOnError> {
        return (options?.client ?? client).post<PerformActionResponses, PerformActionErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/Perform',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static processUpload<ThrowOnError extends boolean = true>(options?: Options<ProcessUploadData, ThrowOnError>): RequestResult<ProcessUploadResponses, ProcessUploadErrors, ThrowOnError> {
        return (options?.client ?? client).post<ProcessUploadResponses, ProcessUploadErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/ProcessUpload',
            ...options
        });
    }
    
    public static running<ThrowOnError extends boolean = true>(options?: Options<RunningData, ThrowOnError>): RequestResult<RunningResponses, RunningErrors, ThrowOnError> {
        return (options?.client ?? client).get<RunningResponses, RunningErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/Running',
            ...options
        });
    }
    
    public static status<ThrowOnError extends boolean = true>(options?: Options<StatusData, ThrowOnError>): RequestResult<StatusResponses, StatusErrors, ThrowOnError> {
        return (options?.client ?? client).get<StatusResponses, StatusErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/Status',
            ...options
        });
    }
}

export class FoldersService {
    public static mergeExportFolder<ThrowOnError extends boolean = true>(options?: Options<MergeExportFolderData, ThrowOnError>): RequestResult<MergeExportFolderResponses, MergeExportFolderErrors, ThrowOnError> {
        return (options?.client ?? client).post<MergeExportFolderResponses, MergeExportFolderErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/MergeExport',
            ...options
        });
    }
}

export class MigrationsService {
    public static checkLegacy<ThrowOnError extends boolean = true>(options?: Options<CheckLegacyData, ThrowOnError>): RequestResult<CheckLegacyResponses, CheckLegacyErrors, ThrowOnError> {
        return (options?.client ?? client).get<CheckLegacyResponses, CheckLegacyErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/CheckLegacy',
            ...options
        });
    }
    
    public static copyLegacy<ThrowOnError extends boolean = true>(options?: Options<CopyLegacyData, ThrowOnError>): RequestResult<CopyLegacyResponses, CopyLegacyErrors, ThrowOnError> {
        return (options?.client ?? client).post<CopyLegacyResponses, CopyLegacyErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/CopyLegacy',
            ...options
        });
    }
    
    public static ignoreLegacy<ThrowOnError extends boolean = true>(options?: Options<IgnoreLegacyData, ThrowOnError>): RequestResult<IgnoreLegacyResponses, IgnoreLegacyErrors, ThrowOnError> {
        return (options?.client ?? client).post<IgnoreLegacyResponses, IgnoreLegacyErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/IgnoreLegacy',
            ...options
        });
    }
}

export class SettingsService {
    public static getAddOns<ThrowOnError extends boolean = true>(options?: Options<GetAddOnsData, ThrowOnError>): RequestResult<GetAddOnsResponses, GetAddOnsErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetAddOnsResponses, GetAddOnsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/AddOns',
            ...options
        });
    }
    
    public static getAddonSplash<ThrowOnError extends boolean = true>(options?: Options<GetAddonSplashData, ThrowOnError>): RequestResult<GetAddonSplashResponses, GetAddonSplashErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetAddonSplashResponses, GetAddonSplashErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/AddOnSplash',
            ...options
        });
    }
    
    public static getHandlerSetSettings<ThrowOnError extends boolean = true>(options?: Options<GetHandlerSetSettingsData, ThrowOnError>): RequestResult<GetHandlerSetSettingsResponses, GetHandlerSetSettingsErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetHandlerSetSettingsResponses, GetHandlerSetSettingsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/HandlerSettings',
            ...options
        });
    }
    
    public static getSets<ThrowOnError extends boolean = true>(options?: Options<GetSetsData, ThrowOnError>): RequestResult<GetSetsResponses, GetSetsErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetSetsResponses, GetSetsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/Sets',
            ...options
        });
    }
    
    public static getSettings<ThrowOnError extends boolean = true>(options?: Options<GetSettingsData, ThrowOnError>): RequestResult<GetSettingsResponses, GetSettingsErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetSettingsResponses, GetSettingsErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/usync/api/v1/Settings',
            ...options
        });
    }
}
