// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetActionsData, GetActionsResponse, DownloadData, DownloadResponse, PerformActionData, PerformActionResponse2, ProcessUploadData, ProcessUploadResponse, CheckLegacyData, CheckLegacyResponse, CopyLegacyData, CopyLegacyResponse, IgnoreLegacyData, IgnoreLegacyResponse, GetAddOnsData, GetAddOnsResponse, GetAddonSplashData, GetAddonSplashResponse, GetHandlerSetSettingsData, GetHandlerSetSettingsResponse, GetSettingsData, GetSettingsResponse } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class ActionsService {
    public static getActions<ThrowOnError extends boolean = true>(options?: Options<GetActionsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetActionsResponse, unknown, ThrowOnError>({
            url: '/umbraco/usync/api/v1/Actions',
            ...options
        });
    }
    
    public static download<ThrowOnError extends boolean = true>(options?: Options<DownloadData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<DownloadResponse, unknown, ThrowOnError>({
            url: '/umbraco/usync/api/v1/Download',
            ...options
        });
    }
    
    public static performAction<ThrowOnError extends boolean = true>(options?: Options<PerformActionData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PerformActionResponse2, unknown, ThrowOnError>({
            url: '/umbraco/usync/api/v1/Perform',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    public static processUpload<ThrowOnError extends boolean = true>(options?: Options<ProcessUploadData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<ProcessUploadResponse, unknown, ThrowOnError>({
            url: '/umbraco/usync/api/v1/ProcessUpload',
            ...options
        });
    }
    
}

export class MigrationsService {
    public static checkLegacy<ThrowOnError extends boolean = true>(options?: Options<CheckLegacyData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<CheckLegacyResponse, unknown, ThrowOnError>({
            url: '/umbraco/usync/api/v1/CheckLegacy',
            ...options
        });
    }
    
    public static copyLegacy<ThrowOnError extends boolean = true>(options?: Options<CopyLegacyData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<CopyLegacyResponse, unknown, ThrowOnError>({
            url: '/umbraco/usync/api/v1/CopyLegacy',
            ...options
        });
    }
    
    public static ignoreLegacy<ThrowOnError extends boolean = true>(options?: Options<IgnoreLegacyData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<IgnoreLegacyResponse, unknown, ThrowOnError>({
            url: '/umbraco/usync/api/v1/IgnoreLegacy',
            ...options
        });
    }
    
}

export class SettingsService {
    public static getAddOns<ThrowOnError extends boolean = true>(options?: Options<GetAddOnsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetAddOnsResponse, unknown, ThrowOnError>({
            url: '/umbraco/usync/api/v1/AddOns',
            ...options
        });
    }
    
    public static getAddonSplash<ThrowOnError extends boolean = true>(options?: Options<GetAddonSplashData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetAddonSplashResponse, unknown, ThrowOnError>({
            url: '/umbraco/usync/api/v1/AddOnSplash',
            ...options
        });
    }
    
    public static getHandlerSetSettings<ThrowOnError extends boolean = true>(options?: Options<GetHandlerSetSettingsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetHandlerSetSettingsResponse, unknown, ThrowOnError>({
            url: '/umbraco/usync/api/v1/HandlerSettings',
            ...options
        });
    }
    
    public static getSettings<ThrowOnError extends boolean = true>(options?: Options<GetSettingsData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetSettingsResponse, unknown, ThrowOnError>({
            url: '/umbraco/usync/api/v1/Settings',
            ...options
        });
    }
    
}