// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { GetActionsResponse, PerformActionData, PerformActionResponse2, CheckLegacyResponse, CopyLegacyResponse, IgnoreLegacyResponse, GetAddOnsResponse, GetAddonSplashResponse, GetHandlerSetSettingsData, GetHandlerSetSettingsResponse, GetSettingsResponse } from './types.gen';

export class ActionsService {
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getActions(): CancelablePromise<GetActionsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/usync/api/v1/Actions'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.requestBody
     * @returns unknown OK
     * @throws ApiError
     */
    public static performAction(data: PerformActionData = {}): CancelablePromise<PerformActionResponse2> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/umbraco/usync/api/v1/Perform',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    
}

export class MigrationsService {
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static checkLegacy(): CancelablePromise<CheckLegacyResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/usync/api/v1/CheckLegacy'
        });
    }
    
    /**
     * @returns boolean OK
     * @throws ApiError
     */
    public static copyLegacy(): CancelablePromise<CopyLegacyResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/umbraco/usync/api/v1/CopyLegacy'
        });
    }
    
    /**
     * @returns boolean OK
     * @throws ApiError
     */
    public static ignoreLegacy(): CancelablePromise<IgnoreLegacyResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/umbraco/usync/api/v1/IgnoreLegacy'
        });
    }
    
}

export class SettingsService {
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getAddOns(): CancelablePromise<GetAddOnsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/usync/api/v1/AddOns'
        });
    }
    
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getAddonSplash(): CancelablePromise<GetAddonSplashResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/usync/api/v1/AddOnSplash'
        });
    }
    
    /**
     * @param data The data for the request.
     * @param data.id
     * @returns unknown OK
     * @throws ApiError
     */
    public static getHandlerSetSettings(data: GetHandlerSetSettingsData = {}): CancelablePromise<GetHandlerSetSettingsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/usync/api/v1/HandlerSettings',
            query: {
                id: data.id
            }
        });
    }
    
    /**
     * @returns unknown OK
     * @throws ApiError
     */
    public static getSettings(): CancelablePromise<GetSettingsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/umbraco/usync/api/v1/Settings'
        });
    }
    
}