// This file is auto-generated by @hey-api/openapi-ts

export enum ChangeDetailType {
    NO_CHANGE = 'NoChange',
    CREATE = 'Create',
    UPDATE = 'Update',
    DELETE = 'Delete',
    ERROR = 'Error',
    WARNING = 'Warning'
}

export enum ChangeType {
    NO_CHANGE = 'NoChange',
    CREATE = 'Create',
    IMPORT = 'Import',
    EXPORT = 'Export',
    UPDATE = 'Update',
    DELETE = 'Delete',
    WILL_CHANGE = 'WillChange',
    INFORMATION = 'Information',
    ROLLEDBACK = 'Rolledback',
    FAIL = 'Fail',
    IMPORT_FAIL = 'ImportFail',
    MISMATCH = 'Mismatch',
    PARENT_MISSING = 'ParentMissing',
    HIDDEN = 'Hidden',
    CLEAN = 'Clean',
    REMOVED = 'Removed'
}

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type HandlerSettings = {
    enabled: boolean;
    actions: Array<string>;
    useFlatStructure: boolean;
    guidNames: boolean;
    failOnMissingParent: boolean;
    group: string;
    createClean: boolean;
    settings: {
        [key: string]: string;
    };
};

export enum HandlerStatus {
    PENDING = 'Pending',
    PROCESSING = 'Processing',
    COMPLETE = 'Complete',
    ERROR = 'Error'
}

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type PerformActionRequest = {
    requestId: string;
    action: string;
    stepNumber: number;
    options?: USyncOptions | null;
    username?: string | null;
};

export type PerformActionResponse = {
    requestId: string;
    status?: Array<SyncHandlerSummary> | null;
    actions?: Array<USyncActionView> | null;
    complete: boolean;
};

export type SyncActionButton = {
    key: string;
    label: string;
    look: string;
    color: string;
    force: boolean;
    clean: boolean;
    file: boolean;
    children: Array<SyncActionButton>;
};

export type SyncActionGroup = {
    key: string;
    icon: string;
    groupName: string;
    buttons: Array<SyncActionButton>;
};

export type SyncHandlerSummary = {
    icon: string;
    name: string;
    status: HandlerStatus;
    changes: number;
    inError: boolean;
};

export type SyncLegacyCheckResponse = {
    hasLegacy: boolean;
    legacyFolder?: string | null;
    legacyTypes: Array<string>;
    latestFolder: string;
    latestVersion: string;
};

export type UploadImportResult = {
    success: boolean;
    errors: Array<string>;
};

export type USyncActionView = {
    key: string;
    name: string;
    handler: string;
    itemType: string;
    change: ChangeType;
    success: boolean;
    details: Array<USyncChange>;
    message?: string | null;
};

export type USyncAddonInfo = {
    version: string;
};

export type USyncAddonSplash = {
    [key: string]: never;
};

export type USyncChange = {
    success: boolean;
    name: string;
    path: string;
    oldValue: string;
    newValue: string;
    change: ChangeDetailType;
};

export type USyncHandlerSetSettings = {
    enabled: boolean;
    handlerGroups: Array<string>;
    disabledHandlers: Array<string>;
    handlerDefaults: HandlerSettings;
    handlers: {
        [key: string]: HandlerSettings;
    };
    isSelectable: boolean;
};

export type USyncOptions = {
    clientId: string;
    force: boolean;
    clean: boolean;
    files: boolean;
    group: string;
    set: string;
};

export type USyncSettings = {
    rootFolder: string;
    folders: Array<string>;
    legacyFolder: string;
    isRootSite: boolean;
    lockRoot: boolean;
    stopFile: string;
    onceFile: string;
    lockRootTypes: Array<string>;
    defaultSet: string;
    importAtStartup: string;
    exportAtStartup: string;
    exportOnSave: string;
    uiEnabledGroups: string;
    reportDebug: boolean;
    addOnPing: boolean;
    rebuildCacheOnCompletion: boolean;
    failOnMissingParent: boolean;
    failOnDuplicates: boolean;
    cacheFolderKeys: boolean;
    showVersionCheckWarning: boolean;
    customMappings: {
        [key: string]: string;
    };
    enableHistory: boolean;
    defaultExtension: string;
    importOnFirstBoot: boolean;
    firstBootGroup: string;
    disableDashboard: boolean;
    summaryDashboard: boolean;
    summaryLimit: number;
    hideAddOns: string;
    disableNotificationSuppression: boolean;
    backgroundNotifications: boolean;
};

export type GetActionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/Actions';
};

export type GetActionsResponses = {
    /**
     * OK
     */
    200: Array<SyncActionGroup>;
};

export type GetActionsResponse = GetActionsResponses[keyof GetActionsResponses];

export type DownloadData = {
    body?: never;
    path?: never;
    query?: {
        requestId?: string;
    };
    url: '/umbraco/usync/api/v1/Download';
};

export type DownloadResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadResponse = DownloadResponses[keyof DownloadResponses];

export type PerformActionData = {
    body?: PerformActionRequest;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/Perform';
};

export type PerformActionResponses = {
    /**
     * OK
     */
    200: PerformActionResponse;
};

export type PerformActionResponse2 = PerformActionResponses[keyof PerformActionResponses];

export type ProcessUploadData = {
    body?: never;
    path?: never;
    query?: {
        tempKey?: string;
    };
    url: '/umbraco/usync/api/v1/ProcessUpload';
};

export type ProcessUploadResponses = {
    /**
     * OK
     */
    200: UploadImportResult;
};

export type ProcessUploadResponse = ProcessUploadResponses[keyof ProcessUploadResponses];

export type CheckLegacyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/CheckLegacy';
};

export type CheckLegacyResponses = {
    /**
     * OK
     */
    200: SyncLegacyCheckResponse;
};

export type CheckLegacyResponse = CheckLegacyResponses[keyof CheckLegacyResponses];

export type CopyLegacyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/CopyLegacy';
};

export type CopyLegacyResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type CopyLegacyResponse = CopyLegacyResponses[keyof CopyLegacyResponses];

export type IgnoreLegacyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/IgnoreLegacy';
};

export type IgnoreLegacyResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type IgnoreLegacyResponse = IgnoreLegacyResponses[keyof IgnoreLegacyResponses];

export type GetAddOnsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/AddOns';
};

export type GetAddOnsResponses = {
    /**
     * OK
     */
    200: USyncAddonInfo;
};

export type GetAddOnsResponse = GetAddOnsResponses[keyof GetAddOnsResponses];

export type GetAddonSplashData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/AddOnSplash';
};

export type GetAddonSplashResponses = {
    /**
     * OK
     */
    200: USyncAddonSplash;
};

export type GetAddonSplashResponse = GetAddonSplashResponses[keyof GetAddonSplashResponses];

export type GetHandlerSetSettingsData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/usync/api/v1/HandlerSettings';
};

export type GetHandlerSetSettingsResponses = {
    /**
     * OK
     */
    200: USyncHandlerSetSettings;
};

export type GetHandlerSetSettingsResponse = GetHandlerSetSettingsResponses[keyof GetHandlerSetSettingsResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/Settings';
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: USyncSettings;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:33331' | (string & {});
};