// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:28580' | (string & {});
};

export type Assembly = {
    readonly definedTypes: Array<TypeInfo>;
    readonly exportedTypes: Array<Type>;
    /**
     * @deprecated
     */
    readonly codeBase?: string | null;
    entryPoint?: MethodInfo | null;
    readonly fullName?: string | null;
    readonly imageRuntimeVersion: string;
    readonly isDynamic: boolean;
    readonly location: string;
    readonly reflectionOnly: boolean;
    readonly isCollectible: boolean;
    readonly isFullyTrusted: boolean;
    readonly customAttributes: Array<CustomAttributeData>;
    /**
     * @deprecated
     */
    readonly escapedCodeBase: string;
    manifestModule: Module;
    readonly modules: Array<Module>;
    /**
     * @deprecated
     */
    readonly globalAssemblyCache: boolean;
    readonly hostContext: number;
    securityRuleSet: SecurityRuleSet;
};

export enum CallingConventions {
    STANDARD = 'Standard',
    VAR_ARGS = 'VarArgs',
    ANY = 'Any',
    HAS_THIS = 'HasThis',
    EXPLICIT_THIS = 'ExplicitThis'
}

export enum ChangeDetailType {
    NO_CHANGE = 'NoChange',
    CREATE = 'Create',
    UPDATE = 'Update',
    DELETE = 'Delete',
    ERROR = 'Error',
    WARNING = 'Warning'
}

export enum ChangeType {
    NO_CHANGE = 'NoChange',
    CREATE = 'Create',
    IMPORT = 'Import',
    EXPORT = 'Export',
    UPDATE = 'Update',
    DELETE = 'Delete',
    WILL_CHANGE = 'WillChange',
    INFORMATION = 'Information',
    ROLLEDBACK = 'Rolledback',
    FAIL = 'Fail',
    IMPORT_FAIL = 'ImportFail',
    MISMATCH = 'Mismatch',
    PARENT_MISSING = 'ParentMissing',
    HIDDEN = 'Hidden',
    CLEAN = 'Clean',
    REMOVED = 'Removed'
}

export type ConstructorInfo = {
    readonly name: string;
    declaringType?: Type | null;
    reflectedType?: Type | null;
    module: Module;
    readonly customAttributes: Array<CustomAttributeData>;
    readonly isCollectible: boolean;
    readonly metadataToken: number;
    attributes: MethodAttributes;
    methodImplementationFlags: MethodImplAttributes;
    callingConvention: CallingConventions;
    readonly isAbstract: boolean;
    readonly isConstructor: boolean;
    readonly isFinal: boolean;
    readonly isHideBySig: boolean;
    readonly isSpecialName: boolean;
    readonly isStatic: boolean;
    readonly isVirtual: boolean;
    readonly isAssembly: boolean;
    readonly isFamily: boolean;
    readonly isFamilyAndAssembly: boolean;
    readonly isFamilyOrAssembly: boolean;
    readonly isPrivate: boolean;
    readonly isPublic: boolean;
    readonly isConstructedGenericMethod: boolean;
    readonly isGenericMethod: boolean;
    readonly isGenericMethodDefinition: boolean;
    readonly containsGenericParameters: boolean;
    methodHandle: RuntimeMethodHandle;
    readonly isSecurityCritical: boolean;
    readonly isSecuritySafeCritical: boolean;
    readonly isSecurityTransparent: boolean;
    memberType: MemberTypes;
};

export type CustomAttributeData = {
    attributeType: Type;
    constructor: ConstructorInfo;
    readonly constructorArguments: Array<CustomAttributeTypedArgument>;
    readonly namedArguments: Array<CustomAttributeNamedArgument>;
};

export type CustomAttributeNamedArgument = {
    memberInfo: MemberInfo;
    typedValue: CustomAttributeTypedArgument;
    readonly memberName: string;
    readonly isField: boolean;
};

export type CustomAttributeTypedArgument = {
    argumentType: Type;
    value?: unknown;
};

export enum EventAttributes {
    NONE = 'None',
    SPECIAL_NAME = 'SpecialName',
    RT_SPECIAL_NAME = 'RTSpecialName',
    RESERVED_MASK = 'ReservedMask'
}

export type EventInfo = {
    readonly name: string;
    declaringType?: Type | null;
    reflectedType?: Type | null;
    module: Module;
    readonly customAttributes: Array<CustomAttributeData>;
    readonly isCollectible: boolean;
    readonly metadataToken: number;
    memberType: MemberTypes;
    attributes: EventAttributes;
    readonly isSpecialName: boolean;
    addMethod?: MethodInfo | null;
    removeMethod?: MethodInfo | null;
    raiseMethod?: MethodInfo | null;
    readonly isMulticast: boolean;
    eventHandlerType?: Type | null;
};

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type Exception = {
    targetSite?: MethodBase | null;
    readonly message: string;
    readonly data: {
        [key: string]: unknown;
    };
    innerException?: Exception | null;
    helpLink?: string | null;
    source?: string | null;
    hResult: number;
    readonly stackTrace?: string | null;
};

export enum FieldAttributes {
    PRIVATE_SCOPE = 'PrivateScope',
    PRIVATE = 'Private',
    FAM_AND_ASSEM = 'FamANDAssem',
    ASSEMBLY = 'Assembly',
    FAMILY = 'Family',
    FAM_OR_ASSEM = 'FamORAssem',
    PUBLIC = 'Public',
    FIELD_ACCESS_MASK = 'FieldAccessMask',
    STATIC = 'Static',
    INIT_ONLY = 'InitOnly',
    LITERAL = 'Literal',
    NOT_SERIALIZED = 'NotSerialized',
    HAS_FIELD_RVA = 'HasFieldRVA',
    SPECIAL_NAME = 'SpecialName',
    RT_SPECIAL_NAME = 'RTSpecialName',
    HAS_FIELD_MARSHAL = 'HasFieldMarshal',
    PINVOKE_IMPL = 'PinvokeImpl',
    HAS_DEFAULT = 'HasDefault',
    RESERVED_MASK = 'ReservedMask'
}

export type FieldInfo = {
    readonly name: string;
    declaringType?: Type | null;
    reflectedType?: Type | null;
    module: Module;
    readonly customAttributes: Array<CustomAttributeData>;
    readonly isCollectible: boolean;
    readonly metadataToken: number;
    memberType: MemberTypes;
    attributes: FieldAttributes;
    fieldType: Type;
    readonly isInitOnly: boolean;
    readonly isLiteral: boolean;
    /**
     * @deprecated
     */
    readonly isNotSerialized: boolean;
    readonly isPinvokeImpl: boolean;
    readonly isSpecialName: boolean;
    readonly isStatic: boolean;
    readonly isAssembly: boolean;
    readonly isFamily: boolean;
    readonly isFamilyAndAssembly: boolean;
    readonly isFamilyOrAssembly: boolean;
    readonly isPrivate: boolean;
    readonly isPublic: boolean;
    readonly isSecurityCritical: boolean;
    readonly isSecuritySafeCritical: boolean;
    readonly isSecurityTransparent: boolean;
    fieldHandle: RuntimeFieldHandle;
};

export enum GenericParameterAttributes {
    NONE = 'None',
    COVARIANT = 'Covariant',
    CONTRAVARIANT = 'Contravariant',
    VARIANCE_MASK = 'VarianceMask',
    REFERENCE_TYPE_CONSTRAINT = 'ReferenceTypeConstraint',
    NOT_NULLABLE_VALUE_TYPE_CONSTRAINT = 'NotNullableValueTypeConstraint',
    DEFAULT_CONSTRUCTOR_CONSTRAINT = 'DefaultConstructorConstraint',
    SPECIAL_CONSTRAINT_MASK = 'SpecialConstraintMask',
    ALLOW_BY_REF_LIKE = 'AllowByRefLike'
}

export type HandlerSettings = {
    enabled: boolean;
    actions: Array<string>;
    useFlatStructure: boolean;
    guidNames: boolean;
    failOnMissingParent: boolean;
    group: string;
    createClean: boolean;
    fullFileOnDifference: boolean;
    settings: {
        [key: string]: unknown;
    };
};

export enum HandlerStatus {
    PENDING = 'Pending',
    PROCESSING = 'Processing',
    COMPLETE = 'Complete',
    ERROR = 'Error'
}

export type ICustomAttributeProvider = {
    [key: string]: never;
};

export type IntPtr = {
    [key: string]: never;
};

export enum LayoutKind {
    SEQUENTIAL = 'Sequential',
    EXPLICIT = 'Explicit',
    AUTO = 'Auto'
}

export type MemberInfo = {
    memberType: MemberTypes;
    readonly name: string;
    declaringType?: Type | null;
    reflectedType?: Type | null;
    module: Module;
    readonly customAttributes: Array<CustomAttributeData>;
    readonly isCollectible: boolean;
    readonly metadataToken: number;
};

export enum MemberTypes {
    CONSTRUCTOR = 'Constructor',
    EVENT = 'Event',
    FIELD = 'Field',
    METHOD = 'Method',
    PROPERTY = 'Property',
    TYPE_INFO = 'TypeInfo',
    CUSTOM = 'Custom',
    NESTED_TYPE = 'NestedType',
    ALL = 'All'
}

export enum MethodAttributes {
    PRIVATE_SCOPE = 'PrivateScope',
    REUSE_SLOT = 'ReuseSlot',
    PRIVATE = 'Private',
    FAM_AND_ASSEM = 'FamANDAssem',
    ASSEMBLY = 'Assembly',
    FAMILY = 'Family',
    FAM_OR_ASSEM = 'FamORAssem',
    PUBLIC = 'Public',
    MEMBER_ACCESS_MASK = 'MemberAccessMask',
    UNMANAGED_EXPORT = 'UnmanagedExport',
    STATIC = 'Static',
    FINAL = 'Final',
    VIRTUAL = 'Virtual',
    HIDE_BY_SIG = 'HideBySig',
    NEW_SLOT = 'NewSlot',
    VTABLE_LAYOUT_MASK = 'VtableLayoutMask',
    CHECK_ACCESS_ON_OVERRIDE = 'CheckAccessOnOverride',
    ABSTRACT = 'Abstract',
    SPECIAL_NAME = 'SpecialName',
    RT_SPECIAL_NAME = 'RTSpecialName',
    PINVOKE_IMPL = 'PinvokeImpl',
    HAS_SECURITY = 'HasSecurity',
    REQUIRE_SEC_OBJECT = 'RequireSecObject',
    RESERVED_MASK = 'ReservedMask'
}

export type MethodBase = {
    memberType: MemberTypes;
    readonly name: string;
    declaringType?: Type | null;
    reflectedType?: Type | null;
    module: Module;
    readonly customAttributes: Array<CustomAttributeData>;
    readonly isCollectible: boolean;
    readonly metadataToken: number;
    attributes: MethodAttributes;
    methodImplementationFlags: MethodImplAttributes;
    callingConvention: CallingConventions;
    readonly isAbstract: boolean;
    readonly isConstructor: boolean;
    readonly isFinal: boolean;
    readonly isHideBySig: boolean;
    readonly isSpecialName: boolean;
    readonly isStatic: boolean;
    readonly isVirtual: boolean;
    readonly isAssembly: boolean;
    readonly isFamily: boolean;
    readonly isFamilyAndAssembly: boolean;
    readonly isFamilyOrAssembly: boolean;
    readonly isPrivate: boolean;
    readonly isPublic: boolean;
    readonly isConstructedGenericMethod: boolean;
    readonly isGenericMethod: boolean;
    readonly isGenericMethodDefinition: boolean;
    readonly containsGenericParameters: boolean;
    methodHandle: RuntimeMethodHandle;
    readonly isSecurityCritical: boolean;
    readonly isSecuritySafeCritical: boolean;
    readonly isSecurityTransparent: boolean;
};

export enum MethodImplAttributes {
    IL = 'IL',
    MANAGED = 'Managed',
    NATIVE = 'Native',
    OPTIL = 'OPTIL',
    CODE_TYPE_MASK = 'CodeTypeMask',
    RUNTIME = 'Runtime',
    MANAGED_MASK = 'ManagedMask',
    UNMANAGED = 'Unmanaged',
    NO_INLINING = 'NoInlining',
    FORWARD_REF = 'ForwardRef',
    SYNCHRONIZED = 'Synchronized',
    NO_OPTIMIZATION = 'NoOptimization',
    PRESERVE_SIG = 'PreserveSig',
    AGGRESSIVE_INLINING = 'AggressiveInlining',
    AGGRESSIVE_OPTIMIZATION = 'AggressiveOptimization',
    INTERNAL_CALL = 'InternalCall',
    ASYNC = 'Async',
    MAX_METHOD_IMPL_VAL = 'MaxMethodImplVal'
}

export type MethodInfo = {
    readonly name: string;
    declaringType?: Type | null;
    reflectedType?: Type | null;
    module: Module;
    readonly customAttributes: Array<CustomAttributeData>;
    readonly isCollectible: boolean;
    readonly metadataToken: number;
    attributes: MethodAttributes;
    methodImplementationFlags: MethodImplAttributes;
    callingConvention: CallingConventions;
    readonly isAbstract: boolean;
    readonly isConstructor: boolean;
    readonly isFinal: boolean;
    readonly isHideBySig: boolean;
    readonly isSpecialName: boolean;
    readonly isStatic: boolean;
    readonly isVirtual: boolean;
    readonly isAssembly: boolean;
    readonly isFamily: boolean;
    readonly isFamilyAndAssembly: boolean;
    readonly isFamilyOrAssembly: boolean;
    readonly isPrivate: boolean;
    readonly isPublic: boolean;
    readonly isConstructedGenericMethod: boolean;
    readonly isGenericMethod: boolean;
    readonly isGenericMethodDefinition: boolean;
    readonly containsGenericParameters: boolean;
    methodHandle: RuntimeMethodHandle;
    readonly isSecurityCritical: boolean;
    readonly isSecuritySafeCritical: boolean;
    readonly isSecurityTransparent: boolean;
    memberType: MemberTypes;
    returnParameter: ParameterInfo;
    returnType: Type;
    returnTypeCustomAttributes: ICustomAttributeProvider;
};

export type Module = {
    assembly: Assembly;
    readonly fullyQualifiedName: string;
    readonly name: string;
    readonly mdStreamVersion: number;
    readonly moduleVersionId: string;
    readonly scopeName: string;
    moduleHandle: ModuleHandle;
    readonly customAttributes: Array<CustomAttributeData>;
    readonly metadataToken: number;
};

export type ModuleHandle = {
    readonly mdStreamVersion: number;
};

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export enum ParameterAttributes {
    NONE = 'None',
    IN = 'In',
    OUT = 'Out',
    LCID = 'Lcid',
    RETVAL = 'Retval',
    OPTIONAL = 'Optional',
    HAS_DEFAULT = 'HasDefault',
    HAS_FIELD_MARSHAL = 'HasFieldMarshal',
    RESERVED3 = 'Reserved3',
    RESERVED4 = 'Reserved4',
    RESERVED_MASK = 'ReservedMask'
}

export type ParameterInfo = {
    attributes: ParameterAttributes;
    member: MemberInfo;
    readonly name?: string | null;
    parameterType: Type;
    readonly position: number;
    readonly isIn: boolean;
    readonly isLcid: boolean;
    readonly isOptional: boolean;
    readonly isOut: boolean;
    readonly isRetval: boolean;
    readonly defaultValue?: unknown;
    readonly rawDefaultValue?: unknown;
    readonly hasDefaultValue: boolean;
    readonly customAttributes: Array<CustomAttributeData>;
    readonly metadataToken: number;
};

export type PerformActionRequest = {
    requestId: string;
    action: string;
    stepNumber: number;
    options?: USyncOptions | null;
    username?: string | null;
};

export type PerformActionResponse = {
    requestId: string;
    status?: Array<SyncHandlerSummary> | null;
    actions?: Array<USyncActionView> | null;
    complete: boolean;
    inBackground: boolean;
};

export enum PropertyAttributes {
    NONE = 'None',
    SPECIAL_NAME = 'SpecialName',
    RT_SPECIAL_NAME = 'RTSpecialName',
    HAS_DEFAULT = 'HasDefault',
    RESERVED2 = 'Reserved2',
    RESERVED3 = 'Reserved3',
    RESERVED4 = 'Reserved4',
    RESERVED_MASK = 'ReservedMask'
}

export type PropertyInfo = {
    readonly name: string;
    declaringType?: Type | null;
    reflectedType?: Type | null;
    module: Module;
    readonly customAttributes: Array<CustomAttributeData>;
    readonly isCollectible: boolean;
    readonly metadataToken: number;
    memberType: MemberTypes;
    propertyType: Type;
    attributes: PropertyAttributes;
    readonly isSpecialName: boolean;
    readonly canRead: boolean;
    readonly canWrite: boolean;
    getMethod?: MethodInfo | null;
    setMethod?: MethodInfo | null;
};

export type RuntimeFieldHandle = {
    value: IntPtr;
};

export type RuntimeMethodHandle = {
    value: IntPtr;
};

export type RuntimeTypeHandle = {
    value: IntPtr;
};

export enum SecurityRuleSet {
    NONE = 'None',
    LEVEL1 = 'Level1',
    LEVEL2 = 'Level2'
}

export type StructLayoutAttribute = {
    readonly typeId: unknown;
    value: LayoutKind;
};

export type SyncActionButton = {
    key: string;
    label: string;
    look: string;
    color: string;
    force: boolean;
    clean: boolean;
    file: boolean;
    children: Array<SyncActionButton>;
};

export type SyncActionGroup = {
    key: string;
    icon: string;
    groupName: string;
    buttons: Array<SyncActionButton>;
};

export enum SyncFolderMode {
    NORMAL = 'Normal',
    ROOT = 'Root',
    PRODUCTION = 'Production'
}

export type SyncHandlerSummary = {
    icon: string;
    name: string;
    status: HandlerStatus;
    changes: number;
    inError: boolean;
};

export type SyncLegacyCheckResponse = {
    hasLegacy: boolean;
    legacyFolder?: string | null;
    legacyTypes: Array<string>;
    latestFolder: string;
    latestVersion: string;
};

export enum SyncProcessingMode {
    NORMAL = 'Normal',
    BACKGROUND = 'Background'
}

export type SyncSelectableSet = {
    name: string;
    settings: USyncHandlerSetSettings;
};

export type Type = {
    readonly name: string;
    readonly customAttributes: Array<CustomAttributeData>;
    readonly isCollectible: boolean;
    readonly metadataToken: number;
    memberType: MemberTypes;
    readonly namespace?: string | null;
    readonly assemblyQualifiedName?: string | null;
    readonly fullName?: string | null;
    assembly: Assembly;
    module: Module;
    readonly isInterface: boolean;
    readonly isNested: boolean;
    declaringType?: Type | null;
    declaringMethod?: MethodBase | null;
    reflectedType?: Type | null;
    underlyingSystemType: Type;
    readonly isTypeDefinition: boolean;
    readonly isArray: boolean;
    readonly isByRef: boolean;
    readonly isPointer: boolean;
    readonly isConstructedGenericType: boolean;
    readonly isGenericParameter: boolean;
    readonly isGenericTypeParameter: boolean;
    readonly isGenericMethodParameter: boolean;
    readonly isGenericType: boolean;
    readonly isGenericTypeDefinition: boolean;
    readonly isSZArray: boolean;
    readonly isVariableBoundArray: boolean;
    readonly isByRefLike: boolean;
    readonly isFunctionPointer: boolean;
    readonly isUnmanagedFunctionPointer: boolean;
    readonly hasElementType: boolean;
    readonly genericTypeArguments: Array<Type>;
    readonly genericParameterPosition: number;
    genericParameterAttributes: GenericParameterAttributes;
    attributes: TypeAttributes;
    readonly isAbstract: boolean;
    readonly isImport: boolean;
    readonly isSealed: boolean;
    readonly isSpecialName: boolean;
    readonly isClass: boolean;
    readonly isNestedAssembly: boolean;
    readonly isNestedFamANDAssem: boolean;
    readonly isNestedFamily: boolean;
    readonly isNestedFamORAssem: boolean;
    readonly isNestedPrivate: boolean;
    readonly isNestedPublic: boolean;
    readonly isNotPublic: boolean;
    readonly isPublic: boolean;
    readonly isAutoLayout: boolean;
    readonly isExplicitLayout: boolean;
    readonly isLayoutSequential: boolean;
    readonly isAnsiClass: boolean;
    readonly isAutoClass: boolean;
    readonly isUnicodeClass: boolean;
    readonly isCOMObject: boolean;
    readonly isContextful: boolean;
    readonly isEnum: boolean;
    readonly isMarshalByRef: boolean;
    readonly isPrimitive: boolean;
    readonly isValueType: boolean;
    readonly isSignatureType: boolean;
    readonly isSecurityCritical: boolean;
    readonly isSecuritySafeCritical: boolean;
    readonly isSecurityTransparent: boolean;
    structLayoutAttribute?: StructLayoutAttribute | null;
    typeInitializer?: ConstructorInfo | null;
    typeHandle: RuntimeTypeHandle;
    readonly guid: string;
    baseType?: Type | null;
    /**
     * @deprecated
     */
    readonly isSerializable: boolean;
    readonly containsGenericParameters: boolean;
    readonly isVisible: boolean;
};

export enum TypeAttributes {
    NOT_PUBLIC = 'NotPublic',
    AUTO_LAYOUT = 'AutoLayout',
    ANSI_CLASS = 'AnsiClass',
    CLASS = 'Class',
    PUBLIC = 'Public',
    NESTED_PUBLIC = 'NestedPublic',
    NESTED_PRIVATE = 'NestedPrivate',
    NESTED_FAMILY = 'NestedFamily',
    NESTED_ASSEMBLY = 'NestedAssembly',
    NESTED_FAM_AND_ASSEM = 'NestedFamANDAssem',
    VISIBILITY_MASK = 'VisibilityMask',
    NESTED_FAM_OR_ASSEM = 'NestedFamORAssem',
    SEQUENTIAL_LAYOUT = 'SequentialLayout',
    EXPLICIT_LAYOUT = 'ExplicitLayout',
    LAYOUT_MASK = 'LayoutMask',
    INTERFACE = 'Interface',
    CLASS_SEMANTICS_MASK = 'ClassSemanticsMask',
    ABSTRACT = 'Abstract',
    SEALED = 'Sealed',
    SPECIAL_NAME = 'SpecialName',
    RT_SPECIAL_NAME = 'RTSpecialName',
    IMPORT = 'Import',
    SERIALIZABLE = 'Serializable',
    WINDOWS_RUNTIME = 'WindowsRuntime',
    UNICODE_CLASS = 'UnicodeClass',
    AUTO_CLASS = 'AutoClass',
    STRING_FORMAT_MASK = 'StringFormatMask',
    CUSTOM_FORMAT_CLASS = 'CustomFormatClass',
    HAS_SECURITY = 'HasSecurity',
    RESERVED_MASK = 'ReservedMask',
    BEFORE_FIELD_INIT = 'BeforeFieldInit',
    CUSTOM_FORMAT_MASK = 'CustomFormatMask'
}

export type TypeInfo = {
    readonly name: string;
    readonly customAttributes: Array<CustomAttributeData>;
    readonly isCollectible: boolean;
    readonly metadataToken: number;
    memberType: MemberTypes;
    readonly namespace?: string | null;
    readonly assemblyQualifiedName?: string | null;
    readonly fullName?: string | null;
    assembly: Assembly;
    module: Module;
    readonly isInterface: boolean;
    readonly isNested: boolean;
    declaringType?: Type | null;
    declaringMethod?: MethodBase | null;
    reflectedType?: Type | null;
    underlyingSystemType: Type;
    readonly isTypeDefinition: boolean;
    readonly isArray: boolean;
    readonly isByRef: boolean;
    readonly isPointer: boolean;
    readonly isConstructedGenericType: boolean;
    readonly isGenericParameter: boolean;
    readonly isGenericTypeParameter: boolean;
    readonly isGenericMethodParameter: boolean;
    readonly isGenericType: boolean;
    readonly isGenericTypeDefinition: boolean;
    readonly isSZArray: boolean;
    readonly isVariableBoundArray: boolean;
    readonly isByRefLike: boolean;
    readonly isFunctionPointer: boolean;
    readonly isUnmanagedFunctionPointer: boolean;
    readonly hasElementType: boolean;
    readonly genericTypeArguments: Array<Type>;
    readonly genericParameterPosition: number;
    genericParameterAttributes: GenericParameterAttributes;
    attributes: TypeAttributes;
    readonly isAbstract: boolean;
    readonly isImport: boolean;
    readonly isSealed: boolean;
    readonly isSpecialName: boolean;
    readonly isClass: boolean;
    readonly isNestedAssembly: boolean;
    readonly isNestedFamANDAssem: boolean;
    readonly isNestedFamily: boolean;
    readonly isNestedFamORAssem: boolean;
    readonly isNestedPrivate: boolean;
    readonly isNestedPublic: boolean;
    readonly isNotPublic: boolean;
    readonly isPublic: boolean;
    readonly isAutoLayout: boolean;
    readonly isExplicitLayout: boolean;
    readonly isLayoutSequential: boolean;
    readonly isAnsiClass: boolean;
    readonly isAutoClass: boolean;
    readonly isUnicodeClass: boolean;
    readonly isCOMObject: boolean;
    readonly isContextful: boolean;
    readonly isEnum: boolean;
    readonly isMarshalByRef: boolean;
    readonly isPrimitive: boolean;
    readonly isValueType: boolean;
    readonly isSignatureType: boolean;
    readonly isSecurityCritical: boolean;
    readonly isSecuritySafeCritical: boolean;
    readonly isSecurityTransparent: boolean;
    structLayoutAttribute?: StructLayoutAttribute | null;
    typeInitializer?: ConstructorInfo | null;
    typeHandle: RuntimeTypeHandle;
    readonly guid: string;
    baseType?: Type | null;
    /**
     * @deprecated
     */
    readonly isSerializable: boolean;
    readonly containsGenericParameters: boolean;
    readonly isVisible: boolean;
    readonly genericTypeParameters: Array<Type>;
    readonly declaredConstructors: Array<ConstructorInfo>;
    readonly declaredEvents: Array<EventInfo>;
    readonly declaredFields: Array<FieldInfo>;
    readonly declaredMembers: Array<MemberInfo>;
    readonly declaredMethods: Array<MethodInfo>;
    readonly declaredNestedTypes: Array<TypeInfo>;
    readonly declaredProperties: Array<PropertyInfo>;
    readonly implementedInterfaces: Array<Type>;
};

export type UploadImportResult = {
    success: boolean;
    errors: Array<string>;
};

export type USyncAction = {
    handlerAlias?: string | null;
    success: boolean;
    itemType: string;
    message?: string | null;
    exception?: Exception | null;
    change: ChangeType;
    fileName?: string | null;
    name: string;
    path?: string | null;
    requiresPostProcessing: boolean;
    detailMessage?: string | null;
    details?: Array<USyncChange> | null;
    key: string;
};

export type USyncActionView = {
    key: string;
    name: string;
    handler: string;
    itemType: string;
    change: ChangeType;
    success: boolean;
    details: Array<USyncChange>;
    message?: string | null;
};

export type USyncAddonInfo = {
    version: string;
};

export type USyncAddonSplash = {
    [key: string]: never;
};

export type USyncChange = {
    success: boolean;
    name: string;
    path: string;
    oldValue: string;
    newValue: string;
    change: ChangeDetailType;
};

export type USyncHandlerSetSettings = {
    enabled: boolean;
    handlerGroups: Array<string>;
    disabledHandlers: Array<string>;
    handlerDefaults: HandlerSettings;
    handlers: {
        [key: string]: HandlerSettings;
    };
    isSelectable: boolean;
};

export type USyncOptions = {
    clientId: string;
    force: boolean;
    clean: boolean;
    files: boolean;
    group: string;
    set: string;
};

export type USyncSettings = {
    rootFolder: string;
    folders: Array<string>;
    legacyFolder: string;
    isRootSite: boolean;
    lockRoot: boolean;
    stopFile: string;
    onceFile: string;
    lockRootTypes: Array<string>;
    backgroundStartup: boolean;
    defaultSet: string;
    importAtStartup: string;
    exportAtStartup: string;
    exportOnSave: string;
    uiEnabledGroups: string;
    reportDebug: boolean;
    addOnPing: boolean;
    rebuildCacheOnCompletion: boolean;
    failOnMissingParent: boolean;
    failOnDuplicates: boolean;
    cacheFolderKeys: boolean;
    showVersionCheckWarning: boolean;
    customMappings: {
        [key: string]: string;
    };
    enableHistory: boolean;
    defaultExtension: string;
    importOnFirstBoot: boolean;
    firstBootGroup: string;
    disableDashboard: boolean;
    summaryDashboard: boolean;
    summaryLimit: number;
    hideAddOns: string;
    disableNotificationSuppression: boolean;
    backgroundNotifications: boolean;
    moveToSection: boolean;
    folderMode: SyncFolderMode;
    processingMode: SyncProcessingMode;
    productionFolder: string;
};

export type AssemblyWritable = {
    securityRuleSet: SecurityRuleSet;
};

export type ConstructorInfoWritable = {
    attributes: MethodAttributes;
    methodImplementationFlags: MethodImplAttributes;
    callingConvention: CallingConventions;
    memberType: MemberTypes;
};

export type CustomAttributeDataWritable = {
    [key: string]: never;
};

export type CustomAttributeNamedArgumentWritable = {
    memberInfo: MemberInfoWritable;
};

export type EventInfoWritable = {
    memberType: MemberTypes;
    attributes: EventAttributes;
};

export type ExceptionWritable = {
    helpLink?: string | null;
    source?: string | null;
    hResult: number;
};

export type FieldInfoWritable = {
    memberType: MemberTypes;
    attributes: FieldAttributes;
};

export type MemberInfoWritable = {
    memberType: MemberTypes;
};

export type MethodBaseWritable = {
    memberType: MemberTypes;
    attributes: MethodAttributes;
    methodImplementationFlags: MethodImplAttributes;
    callingConvention: CallingConventions;
};

export type MethodInfoWritable = {
    attributes: MethodAttributes;
    methodImplementationFlags: MethodImplAttributes;
    callingConvention: CallingConventions;
    memberType: MemberTypes;
    returnTypeCustomAttributes: ICustomAttributeProvider;
};

export type ModuleWritable = {
    [key: string]: never;
};

export type ParameterInfoWritable = {
    attributes: ParameterAttributes;
};

export type PropertyInfoWritable = {
    memberType: MemberTypes;
    attributes: PropertyAttributes;
};

export type StructLayoutAttributeWritable = {
    value: LayoutKind;
};

export type TypeWritable = {
    memberType: MemberTypes;
    genericParameterAttributes: GenericParameterAttributes;
    attributes: TypeAttributes;
};

export type TypeInfoWritable = {
    memberType: MemberTypes;
    genericParameterAttributes: GenericParameterAttributes;
    attributes: TypeAttributes;
};

export type GetActionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/Actions';
};

export type GetActionsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetActionsResponses = {
    /**
     * OK
     */
    200: Array<SyncActionGroup>;
};

export type GetActionsResponse = GetActionsResponses[keyof GetActionsResponses];

export type GetActionsBySetData = {
    body?: never;
    path?: never;
    query?: {
        setName?: string;
    };
    url: '/umbraco/usync/api/v1/ActionsBySet';
};

export type GetActionsBySetErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetActionsBySetResponses = {
    /**
     * OK
     */
    200: Array<SyncActionGroup>;
};

export type GetActionsBySetResponse = GetActionsBySetResponses[keyof GetActionsBySetResponses];

export type DownloadData = {
    body?: never;
    path?: never;
    query?: {
        requestId?: string;
    };
    url: '/umbraco/usync/api/v1/Download';
};

export type DownloadErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type DownloadResponses = {
    /**
     * OK
     */
    200: Blob | File;
};

export type DownloadResponse = DownloadResponses[keyof DownloadResponses];

export type ImportSingleData = {
    body?: USyncActionView;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/Import';
};

export type ImportSingleErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ImportSingleResponses = {
    /**
     * OK
     */
    200: USyncAction;
};

export type ImportSingleResponse = ImportSingleResponses[keyof ImportSingleResponses];

export type PerformActionData = {
    body?: PerformActionRequest;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/Perform';
};

export type PerformActionErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PerformActionResponses = {
    /**
     * OK
     */
    200: PerformActionResponse;
};

export type PerformActionResponse2 = PerformActionResponses[keyof PerformActionResponses];

export type ProcessUploadData = {
    body?: never;
    path?: never;
    query?: {
        tempKey?: string;
    };
    url: '/umbraco/usync/api/v1/ProcessUpload';
};

export type ProcessUploadErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ProcessUploadResponses = {
    /**
     * OK
     */
    200: UploadImportResult;
};

export type ProcessUploadResponse = ProcessUploadResponses[keyof ProcessUploadResponses];

export type MergeExportFolderData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/MergeExport';
};

export type MergeExportFolderErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type MergeExportFolderResponses = {
    /**
     * OK
     */
    200: number;
};

export type MergeExportFolderResponse = MergeExportFolderResponses[keyof MergeExportFolderResponses];

export type CheckLegacyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/CheckLegacy';
};

export type CheckLegacyErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CheckLegacyResponses = {
    /**
     * OK
     */
    200: SyncLegacyCheckResponse;
};

export type CheckLegacyResponse = CheckLegacyResponses[keyof CheckLegacyResponses];

export type CopyLegacyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/CopyLegacy';
};

export type CopyLegacyErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type CopyLegacyResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type CopyLegacyResponse = CopyLegacyResponses[keyof CopyLegacyResponses];

export type IgnoreLegacyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/IgnoreLegacy';
};

export type IgnoreLegacyErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type IgnoreLegacyResponses = {
    /**
     * OK
     */
    200: boolean;
};

export type IgnoreLegacyResponse = IgnoreLegacyResponses[keyof IgnoreLegacyResponses];

export type GetAddOnsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/AddOns';
};

export type GetAddOnsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAddOnsResponses = {
    /**
     * OK
     */
    200: USyncAddonInfo;
};

export type GetAddOnsResponse = GetAddOnsResponses[keyof GetAddOnsResponses];

export type GetAddonSplashData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/AddOnSplash';
};

export type GetAddonSplashErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetAddonSplashResponses = {
    /**
     * OK
     */
    200: USyncAddonSplash;
};

export type GetAddonSplashResponse = GetAddonSplashResponses[keyof GetAddonSplashResponses];

export type GetHandlerSetSettingsData = {
    body?: never;
    path?: never;
    query?: {
        id?: string;
    };
    url: '/umbraco/usync/api/v1/HandlerSettings';
};

export type GetHandlerSetSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetHandlerSetSettingsResponses = {
    /**
     * OK
     */
    200: USyncHandlerSetSettings;
};

export type GetHandlerSetSettingsResponse = GetHandlerSetSettingsResponses[keyof GetHandlerSetSettingsResponses];

export type GetSetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/Sets';
};

export type GetSetsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSetsResponses = {
    /**
     * OK
     */
    200: Array<SyncSelectableSet>;
};

export type GetSetsResponse = GetSetsResponses[keyof GetSetsResponses];

export type GetSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/usync/api/v1/Settings';
};

export type GetSettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetSettingsResponses = {
    /**
     * OK
     */
    200: USyncSettings;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];
