<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release'"> 
    <Compile Remove="Example\**" />
    <EmbeddedResource Remove="Example\**" />
    <None Remove="Example\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\uSync.BackOffice\uSync.BackOffice.csproj" />
    <ProjectReference Include="..\uSync.Core\uSync.Core.csproj" />
  </ItemGroup>

</Project>
