name: package usync

on: [push]

jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      OUT_FOLDER: './out'


    runs-on: windows-latest
    strategy:
      matrix: 
        dotnet-versions: ['6.0']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK ${{matrix.dotnet-versions}}
        uses: actions/setup-dotnet@v1.9.0
        with:
          dotnet-version: ${{matrix.dotnet-versions}}

      - name: Install gitversion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'

      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.11

      - name: Install dependencies
        run: dotnet restore 

      - name: pack 
        run: dotnet pack .\uSync.Core\uSync.Core.csproj --no-restore -c ${{ env.BUILD_CONFIG }} -o ${{ env.OUT_FOLDER }}  /p:ContinuousIntegrationBuild=true,version=${{ env.GitVersion_SemVer }}
        
      - name: upload artifact 
        uses: actions/upload-artifact@v2
        with:
          name: nupkg
          path: ./out/*.nupkg